### ISSUE TITLE
Cannot find module 'winston-transport'

### ISSUE THREAD

**Issue by Nostreim** [synapsestudios/winston-sentry#24]
I got the following error message after a recent install:
```js
api_1           | Error: Cannot find module 'winston-transport'
api_1           | Require stack:
api_1           | - /src/api/node_modules/@synapsestudios/winston-sentry/index.js
api_1           | - /src/api/src/lib/logger.js
api_1           | - /src/api/manifest.js
api_1           | - /src/api/server.js
api_1           |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:954:17)
api_1           |     at Function.Module._load (internal/modules/cjs/loader.js:847:27)
api_1           |     at Module.require (internal/modules/cjs/loader.js:1016:19)
api_1           |     at require (internal/modules/cjs/helpers.js:69:18)
api_1           |     at Object.<anonymous> (/src/api/node_modules/@synapsestudios/winston-sentry/index.js:2:19)
api_1           |     at Module._compile (internal/modules/cjs/loader.js:1121:30)
api_1           |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
api_1           |     at Module.load (internal/modules/cjs/loader.js:976:32)
api_1           |     at Function.Module._load (internal/modules/cjs/loader.js:884:14)
api_1           |     at Module.require (internal/modules/cjs/loader.js:1016:19)
```

It looks like there is a missing dependency in package.json for winston-transport. winston-transport is under devDependencies instead of dependencies:

```json
  "dependencies": {
    "lodash": "^4.17.15"
  },
  "peerDependencies": {
    "winston-transport": "4.x"
  },
  "devDependencies": {
    "eslint": "^6.8.0",
    "eslint-plugin-jest": "^23.7.0",
    "jest": "^25.1.0",
    "winston-transport": "^4.3.0"
  }
```

**Comment by bobeagan** [comment]
Was not using the correct version of this package for the version of hapi in use, switching back to v1.x of this package works fine
